### ISSUE TITLE
Adding NPM packages to image

### ISSUE THREAD

**Issue by bo01ean** [arduino/openwrt-yun#33]
Is there a documented method to add an npm package to the build process?

I am looking to add buffertools specifically.

**Comment by ffissore** [comment]
There is no particular method. It's a normal openwrt package. Start from one of the node-* you find [here](https://github.com/arduino/openwrt-packages-yun/tree/master/arduino) and modify it appropriately

**Comment by bo01ean** [comment]
sweet, I'll take a look.
