### ISSUE TITLE
Latest code build (master) fails in ruby package

### ISSUE THREAD

**Issue by ndupreez** [arduino/openwrt-yun#34]
When attempting to build the latest version of the code:

ndupreez@debian:~/wspace/x/openwrt-yun$ git branch
* master
ndupreez@debian:~/wspace/x/openwrt-yun$ git log
commit df3fb78f227e3a8ceced842673ee492191cdf0c3
Author: Federico Fissore <federico@fsfe.org>
Date:   Sun Dec 14 09:12:01 2014 +0100

    Update ChangeLog

It failed to find the ruby package:
`--2015-01-14 16:48:54--  http://downloads.openwrt.org/sources/ruby-1.9.3-p429.tar.bz2
Resolving downloads.openwrt.org (downloads.openwrt.org)... 78.24.191.177
Connecting to downloads.openwrt.org (downloads.openwrt.org)|78.24.191.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-01-14 16:48:55 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
make[3]: *** [/home/ndupreez/wspace/x/openwrt-yun/dl/ruby-1.9.3-p429.tar.bz2] Error 2
make[3]: Leaving directory /home/ndupreez/wspace/x/openwrt-yun/feeds/packages/lang/ruby'`

When I download it manually (from ruby-lang) and copy it into the DL_FOLDER directly, it builds, but  then fails missing some libraries:
`Package ruby-core is missing dependencies for the following libraries:
librt.so.0
libruby.so.1.9
make[3]: *** [/home/ndupreez/wspace/x/openwrt-yun/bin/ar71xx/packages/ruby-core_1.9.3-p429-2_ar71xx.ipk] Error 1`

I looked in the OpenWRT sources directory and that particular version isn't present anymore.

Any thoughts?

This is on Debian Wheezy (but I get the same error on Ubuntu 14.04LTS)

**Comment by RedSnake64** [comment]
Did you try the following solution?
https://github.com/arduino/openwrt-packages-yun/pull/24

**Comment by sngl** [comment]
This commit fixes the issue https://github.com/arduino/openwrt-packages-yun/commit/9617fa20e0888321e0ed262a17056c9a54ea866c
