### ISSUE TITLE
opkg update (host unreachable)

### ISSUE THREAD

**Issue by gandarez** [arduino/openwrt-yun#40]
I can’t reach http://download.linino.org

Pinging download.linino.org [88.198.63.58] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 88.198.63.58:
Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

**Comment by ffissore** [comment]
Linino has been replaced by OpenWRT-Yun on April 23rd, 2014 (more than an year ago).
See https://blog.arduino.cc/2014/04/23/upgrading-the-openwrt-yun-image-on-the-yun/
Please upgrade your yun following these instructions http://www.arduino.cc/en/Tutorial/YunSysupgrade

**Comment by gandarez** [comment]
@ffissore Why they downgraded the UI interface? Linino had a beautiful Bootstraper UI.

**Comment by ffissore** [comment]
We haven't downgraded anything. Bootstrap theme is an option we kept disabled in order to save disk space

**Comment by gandarez** [comment]
@ffissore Is there a way to enable it after had installed? or Do I need to compile my own image in order to enable it?

**Comment by ffissore** [comment]
Of course: `opkg install luci-theme-bootstrap`

**Comment by gandarez** [comment]
@ffissore Thanks for answering.

**Comment by gandarez** [comment]
@ffissore after installed the webpage gets timeout when loading.

http://192.168.1.60/cgi-bin/luci/webpanel/homepage

This webpage is not available
ERR_CONNECTION_TIMED_OUT
