### ISSUE TITLE
Yun: Bonjour service (ip resolution) does not work on yun.

### ISSUE THREAD

**Issue by ffissore** [arduino/openwrt-yun#7]
<a href="https://github.com/jantje"><img src="https://avatars.githubusercontent.com/u/1175841?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jantje](https://github.com/jantje)**
_Saturday Dec 07, 2013 at 15:03 GMT_
_Originally opened as https://github.com/arduino/linino/issues/16_

---

When you have 2 yuns on the same network called yun1 and yun2 it is not possible to ping yun2 from yun1 using
ping yun2.local
yun2.local is not resolved to a ip adress.
Pinging with the ip adress works fine.
This issue is discussed here http://forum.arduino.cc/index.php?topic=202577.msg1492883#msg1492883
it seems like the service nss-mdns is missing.

I think this is a important feature when you have multiple yun's on the same network who need to work together.
I for instance need it to have my robot(s) communicating with a base station.

The alternative's I know are
1) using the work around parsing avahi-resolve -n yunX
2) Using fixed IP adresses
I find both workarounds very clumsy.
Therefore I think this is important for the yun that this issue is fixed.

Best regards
Jantje

**Comment by drasko** [comment]
Do we have solution to his? Or it is still impossible to resolve the name from within OpenWrt?

**Comment by tigoe** [comment]
It's been working okay for me. I can't reproduce the problem, sorry.

sent on the go. please excuse brevity and mistaken auto corrections

**Comment by drasko** [comment]
@tigoe what do you use? `nss-mdns` is not present in Chaos Calmer because it depends on glibc.

**Comment by tigoe** [comment]
Caveat: been a couple months since I checked. But I didn't install anything
special. I was just using whatever mdns lib is in the current yun dist and
it showed up on my networks fine.

sent on the go. please excuse brevity and mistaken auto corrections

**Comment by jantje** [comment]
The script I provided works fine.

**Comment by drasko** [comment]
@jantje is it integrated in the source tree? What's the location?

**Comment by jantje** [comment]
The code is here available on this page. a couple of messages above
